Repository r-hyperspec/hyperSpec, pull requests merged in 2021-07, with the labels that each got.

#10 Remove file import unit tests
  DESCRIPTION
  R/DEPRECATED-read.ENVI.HySpex.R
  R/DEPRECATED-read.ENVI.Nicolet.R
  R/DEPRECATED-read.ENVI.R
  R/DEPRECATED-read.asc.Andor.R
  R/DEPRECATED-read.asc.PerkinElmer.R
  R/DEPRECATED-read.ini.R
  R/DEPRECATED-read.mat.Cytospec.R
  R/DEPRECATED-read.mat.Witec.R
  R/DEPRECATED-read.spc.Kaiser.R
  R/DEPRECATED-read.spc.R
  R/DEPRECATED-read.spe.R
  R/DEPRECATED-read.txt.Horiba.R
  R/DEPRECATED-read.txt.Renishaw.R
  R/DEPRECATED-read.txt.Shimadzu.R
  R/DEPRECATED-read.txt.long.R
  R/DEPRECATED-read.txt.wide.R
  R/DEPRECATED-wc.R
  R/hy_unittest.R
Labels: Topic: unit test :one:

#24 Update style: apply styler
  R/Compare.R
  R/DEPRECATED-dist_pearson.R
  R/DEPRECATED-ggplot2.R
  R/DEPRECATED-read.ENVI.HySpex.R
  R/DEPRECATED-read.ENVI.Nicolet.R
  R/DEPRECATED-read.ENVI.R
  R/DEPRECATED-read.asc.Andor.R
  R/DEPRECATED-read.asc.PerkinElmer.R
  R/DEPRECATED-read.ini.R
  R/DEPRECATED-read.jdx.R
  R/DEPRECATED-read.mat.Cytospec.R
  R/DEPRECATED-read.mat.Witec.R
  R/DEPRECATED-read.spc.Kaiser.R
  R/DEPRECATED-read.spc.R
  R/DEPRECATED-read.spe.R
  R/DEPRECATED-read.txt.Horiba.R
  R/DEPRECATED-read.txt.Renishaw.R
  R/DEPRECATED-read.txt.Shimadzu.R
  R/DEPRECATED-read.txt.Witec.R
  R/DEPRECATED-read.txt.long.R
  R/DEPRECATED-read.txt.wide.R
  R/DEPRECATED-scan.R
  R/DEPRECATED-spc_bin.R
  R/DEPRECATED-spc_fit_poly.R
  R/DEPRECATED-spc_na_approx.R
  R/DEPRECATED-wl_convert_units.R
  R/DEPRECATED-wl_eval.R
  R/DEPRECATED-write_txt_long.R
  R/DEPRECATED-write_txt_wide.R
  R/Summary.R
  R/aggregate.R
  R/cov.R
  R/extract.R
  R/hy_list_available_hySpc_packages.R
  R/levelplot.R
  R/map_sel_poly.R
  R/mean_sd.R
  R/palette_colorblind.R
  R/plot.R
  R/plotspc.R
  R/replace.R
  R/rmmvnorm.R
  R/spc_identify.R
  R/vandermonde.R
  R/wl_convert_units.R
  R/zzz.R
  tests/testthat/test-attached.R
Labels: Topic: style :pencil2:

#25 Feature/8 rmmvnorm
  R/rmmvnorm.R
Labels: Topic: documentation :blue_book:
